#===========================#
# Example configuration file
#===========================#

# Images and fonts
# @Required
content:
  images: # !!! SVG is not supported !!!
    background_tile: content/tile.png # https://shikimori.one/assets/background/square_bg.png
    star: content/star.png # Rating star image, png, with alpha channel
    logo: # Shikimori's logo contains two parts
      glyph: content/shikimori-glyph.png
      text: content/shikimori-logo.png
  fonts: # Must use TrueType fonts
    text: content/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf
    bold_text: content/Open_Sans/static/OpenSans/OpenSans-Bold.ttf
    numbers: content/Tahoma/tahoma.ttf
    japanese: content/Noto_Serif_JP/NotoSerifJP-Bold.otf # For cases, when text contains Japanese symbols

# Main colors
# @Optional
colors:
  background: '#ffffff'
  text: '#343434'
  year: '#555555' # Color of year's text (ex: 1996)

  rating: # Colors for score's stars
    active: '#4c86c8'
    regular: '#cccccc'

# Facebook/Twitter/Google/Telegram has recommended image size:
# - 'big'   = 1200x630
# - 'small' = 600x315
#
# 1200x630 is preferable
# @Optional
size: 'big'